/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pbo_2301082020.p280524;

/**
 *
 * @author Administrator
 */
public class calculator extends javax.swing.JFrame {

    /**
     * Creates new form calculator
     */
    String bilangan;
    int jumlah, bil1, bil2;
    float bagi1,bagi2;
    int pilih;

    public calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnButton4 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        btnButtonBackSpace = new javax.swing.JButton();
        btnButtonPersen = new javax.swing.JButton();
        btnButtonBagi = new javax.swing.JButton();
        btnButtonAllClear = new javax.swing.JButton();
        btnButton9 = new javax.swing.JButton();
        btnButton7 = new javax.swing.JButton();
        btnButton8 = new javax.swing.JButton();
        btnButtonKali = new javax.swing.JButton();
        btnButtonKurang = new javax.swing.JButton();
        btnButton6 = new javax.swing.JButton();
        btnButton5 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        btnButtonSamaDengan = new javax.swing.JButton();
        btnButton0 = new javax.swing.JButton();
        btnButton2 = new javax.swing.JButton();
        btnButton1 = new javax.swing.JButton();
        btnButton3 = new javax.swing.JButton();
        btnButtonTambah = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(null);

        btnButton4.setBackground(new java.awt.Color(0, 0, 0));
        btnButton4.setToolTipText("");

        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setBorder(null);

        btnButtonBackSpace.setBackground(new java.awt.Color(153, 153, 153));
        btnButtonBackSpace.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        btnButtonBackSpace.setForeground(new java.awt.Color(255, 255, 255));
        btnButtonBackSpace.setText("<-");
        btnButtonBackSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnButtonBackSpaceActionPerformed(evt);
            }
        });

        btnButtonPersen.setBackground(new java.awt.Color(153, 153, 153));
        btnButtonPersen.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        btnButtonPersen.setForeground(new java.awt.Color(255, 255, 255));
        btnButtonPersen.setText("%");
        btnButtonPersen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnButtonPersenActionPerformed(evt);
            }
        });

        btnButtonBagi.setBackground(new java.awt.Color(255, 153, 0));
        btnButtonBagi.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        btnButtonBagi.setForeground(new java.awt.Color(255, 255, 255));
        btnButtonBagi.setText("/");
        btnButtonBagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnButtonBagiActionPerformed(evt);
            }
        });

        btnButtonAllClear.setBackground(new java.awt.Color(153, 153, 153));
        btnButtonAllClear.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        btnButtonAllClear.setForeground(new java.awt.Color(255, 255, 255));
        btnButtonAllClear.setText("AC");
        btnButtonAllClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnButtonAllClearActionPerformed(evt);
            }
        });

        btnButton9.setBackground(new java.awt.Color(102, 102, 102));
        btnButton9.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        btnButton9.setForeground(new java.awt.Color(255, 255, 255));
        btnButton9.setText("9");
        btnButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnButton9ActionPerformed(evt);
            }
        });

        btnButton7.setBackground(new java.awt.Color(102, 102, 102));
        btnButton7.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        btnButton7.setForeground(new java.awt.Color(255, 255, 255));
        btnButton7.setText("7");
        btnButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnButton7ActionPerformed(evt);
            }
        });

        btnButton8.setBackground(new java.awt.Color(102, 102, 102));
        btnButton8.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        btnButton8.setForeground(new java.awt.Color(255, 255, 255));
        btnButton8.setText("8");
        btnButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnButton8ActionPerformed(evt);
            }
        });

        btnButtonKali.setBackground(new java.awt.Color(255, 153, 0));
        btnButtonKali.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        btnButtonKali.setForeground(new java.awt.Color(255, 255, 255));
        btnButtonKali.setText("X");
        btnButtonKali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnButtonKaliActionPerformed(evt);
            }
        });

        btnButtonKurang.setBackground(new java.awt.Color(255, 153, 0));
        btnButtonKurang.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        btnButtonKurang.setForeground(new java.awt.Color(255, 255, 255));
        btnButtonKurang.setText("-");
        btnButtonKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnButtonKurangActionPerformed(evt);
            }
        });

        btnButton6.setBackground(new java.awt.Color(102, 102, 102));
        btnButton6.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        btnButton6.setForeground(new java.awt.Color(255, 255, 255));
        btnButton6.setText("6");
        btnButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnButton6ActionPerformed(evt);
            }
        });

        btnButton5.setBackground(new java.awt.Color(102, 102, 102));
        btnButton5.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        btnButton5.setForeground(new java.awt.Color(255, 255, 255));
        btnButton5.setText("5");
        btnButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnButton5ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(102, 102, 102));
        jButton13.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("4");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        btnButtonSamaDengan.setBackground(new java.awt.Color(255, 153, 0));
        btnButtonSamaDengan.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        btnButtonSamaDengan.setForeground(new java.awt.Color(255, 255, 255));
        btnButtonSamaDengan.setText("=");
        btnButtonSamaDengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnButtonSamaDenganActionPerformed(evt);
            }
        });

        btnButton0.setBackground(new java.awt.Color(102, 102, 102));
        btnButton0.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        btnButton0.setForeground(new java.awt.Color(255, 255, 255));
        btnButton0.setText("0");
        btnButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnButton0ActionPerformed(evt);
            }
        });

        btnButton2.setBackground(new java.awt.Color(102, 102, 102));
        btnButton2.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        btnButton2.setForeground(new java.awt.Color(255, 255, 255));
        btnButton2.setText("2");
        btnButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnButton2ActionPerformed(evt);
            }
        });

        btnButton1.setBackground(new java.awt.Color(102, 102, 102));
        btnButton1.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        btnButton1.setForeground(new java.awt.Color(255, 255, 255));
        btnButton1.setText("1");
        btnButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnButton1ActionPerformed(evt);
            }
        });

        btnButton3.setBackground(new java.awt.Color(102, 102, 102));
        btnButton3.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        btnButton3.setForeground(new java.awt.Color(255, 255, 255));
        btnButton3.setText("3");
        btnButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnButton3ActionPerformed(evt);
            }
        });

        btnButtonTambah.setBackground(new java.awt.Color(255, 153, 0));
        btnButtonTambah.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        btnButtonTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnButtonTambah.setText("+");
        btnButtonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnButtonTambahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnButton4Layout = new javax.swing.GroupLayout(btnButton4);
        btnButton4.setLayout(btnButton4Layout);
        btnButton4Layout.setHorizontalGroup(
            btnButton4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnButton4Layout.createSequentialGroup()
                .addGroup(btnButton4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnButton4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(btnButton4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(btnButton4Layout.createSequentialGroup()
                                .addGroup(btnButton4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnButtonBackSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(btnButton4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnButtonAllClear, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(btnButton4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnButtonPersen, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                    .addComponent(btnButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(btnButton4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnButtonKali, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                    .addComponent(btnButtonBagi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(btnButton4Layout.createSequentialGroup()
                                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnButtonKurang, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(btnButton4Layout.createSequentialGroup()
                                .addComponent(btnButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnButtonTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(btnButton4Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(btnButton4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnButtonSamaDengan, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        btnButton4Layout.setVerticalGroup(
            btnButton4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnButton4Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(btnButton4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnButtonBackSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnButtonPersen, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnButtonBagi, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnButtonAllClear, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(btnButton4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnButtonKali, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(btnButton4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnButtonKurang, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(btnButton4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnButtonTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(btnButton4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnButtonSamaDengan, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        getContentPane().add(btnButton4);
        btnButton4.setBounds(0, 0, 350, 600);

        setSize(new java.awt.Dimension(340, 605));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnButton1ActionPerformed
        bilangan += "1";
        jTextField1.setText(bilangan);
    }//GEN-LAST:event_btnButton1ActionPerformed

    private void btnButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnButton0ActionPerformed
        bilangan += "0";
        jTextField1.setText(bilangan);
    }//GEN-LAST:event_btnButton0ActionPerformed

    private void btnButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnButton2ActionPerformed
        bilangan += "2";
        jTextField1.setText(bilangan);
    }//GEN-LAST:event_btnButton2ActionPerformed

    private void btnButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnButton3ActionPerformed
        bilangan += "3";
        jTextField1.setText(bilangan);
    }//GEN-LAST:event_btnButton3ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        bilangan += "4";
        jTextField1.setText(bilangan);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void btnButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnButton5ActionPerformed
        bilangan += "5";
        jTextField1.setText(bilangan);
    }//GEN-LAST:event_btnButton5ActionPerformed

    private void btnButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnButton6ActionPerformed
        bilangan += "6";
        jTextField1.setText(bilangan);
    }//GEN-LAST:event_btnButton6ActionPerformed

    private void btnButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnButton7ActionPerformed
        bilangan += "7";
        jTextField1.setText(bilangan);
    }//GEN-LAST:event_btnButton7ActionPerformed

    private void btnButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnButton8ActionPerformed
        bilangan += "8";
        jTextField1.setText(bilangan);
    }//GEN-LAST:event_btnButton8ActionPerformed

    private void btnButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnButton9ActionPerformed
        bilangan += "9";
        jTextField1.setText(bilangan);
    }//GEN-LAST:event_btnButton9ActionPerformed

    private void btnButtonSamaDenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnButtonSamaDenganActionPerformed
        switch (pilih) {
            case 1:
                bil2 = Integer.parseInt(String.valueOf(jTextField1.getText()));
                jumlah = bil1 + bil2;
                bilangan = Integer.toString(jumlah);
                break;
            case 2:
                bil2 = Integer.parseInt(String.valueOf(jTextField1.getText()));
                jumlah = bil1 - bil2;
                bilangan = Integer.toString(jumlah);
                break;
            case 3:
                bil2 = Integer.parseInt(String.valueOf(jTextField1.getText()));
                jumlah = bil1 * bil2;
                bilangan = Integer.toString(jumlah);
                break;
            case 4:
                bil2 = Integer.parseInt(String.valueOf(jTextField1.getText()));
                jumlah = bil1 / bil2;
                bilangan = Integer.toString(jumlah);
                break;
        }
        jTextField1.setText(bilangan);
    }//GEN-LAST:event_btnButtonSamaDenganActionPerformed

    private void btnButtonKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnButtonKurangActionPerformed
        bil1 = Integer.parseInt(bilangan);
        jTextField1.setText("-");
        bilangan = "";
        pilih = 2;
    }//GEN-LAST:event_btnButtonKurangActionPerformed

    private void btnButtonKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnButtonKaliActionPerformed
        bil1 = Integer.parseInt(bilangan);
        jTextField1.setText("*");
        bilangan = "";
        pilih = 3;
    }//GEN-LAST:event_btnButtonKaliActionPerformed

    private void btnButtonBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnButtonBagiActionPerformed
        bil1 = Integer.parseInt(bilangan);
        jTextField1.setText("/");
        bilangan = "";
        pilih = 4;
    }//GEN-LAST:event_btnButtonBagiActionPerformed

    private void btnButtonPersenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnButtonPersenActionPerformed
     
    }//GEN-LAST:event_btnButtonPersenActionPerformed

    private void btnButtonAllClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnButtonAllClearActionPerformed
        jTextField1.setText(null);
        bil1 = 0;
        bil2 = 0;
        jumlah = 0;
        bilangan = "";
    }//GEN-LAST:event_btnButtonAllClearActionPerformed

    private void btnButtonBackSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnButtonBackSpaceActionPerformed
        String currentText = jTextField1.getText();
        if (!currentText.equals("")) {
            jTextField1.setText(currentText.substring(0, currentText.length() - 1));
        }
    }//GEN-LAST:event_btnButtonBackSpaceActionPerformed

    private void btnButtonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnButtonTambahActionPerformed
        bil1 = Integer.parseInt(bilangan);
        jTextField1.setText("+");
        bilangan = "";
        pilih = 1;
    }//GEN-LAST:event_btnButtonTambahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculator().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnButton0;
    private javax.swing.JButton btnButton1;
    private javax.swing.JButton btnButton2;
    private javax.swing.JButton btnButton3;
    private javax.swing.JPanel btnButton4;
    private javax.swing.JButton btnButton5;
    private javax.swing.JButton btnButton6;
    private javax.swing.JButton btnButton7;
    private javax.swing.JButton btnButton8;
    private javax.swing.JButton btnButton9;
    private javax.swing.JButton btnButtonAllClear;
    private javax.swing.JButton btnButtonBackSpace;
    private javax.swing.JButton btnButtonBagi;
    private javax.swing.JButton btnButtonKali;
    private javax.swing.JButton btnButtonKurang;
    private javax.swing.JButton btnButtonPersen;
    private javax.swing.JButton btnButtonSamaDengan;
    private javax.swing.JButton btnButtonTambah;
    private javax.swing.JButton jButton13;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
